# Generated by Django 6.0 on 2026-01-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0002_alter_membership_user_alter_session_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
