# Generated by Django 6.0 on 2026-01-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0003_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='affiliation',
            field=models.CharField(choices=[('CENTER', '중앙 동아리'), ('COLLEGE', '단과대 밴드'), ('MAJOR', '학과 밴드'), ('INDIE', '독립 밴드'), ('ETC', '기타')], default='ETC', max_length=20, verbose_name='소속 분류'),
        ),
        migrations.AddField(
            model_name='band',
            name='affiliation_detail',
            field=models.CharField(blank=True, max_length=50, verbose_name='소속 상세 (직접 입력)'),
        ),
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.TextField(blank=True, verbose_name='상세 소개'),
        ),
        migrations.AddField(
            model_name='band',
            name='introduce',
            field=models.CharField(blank=True, max_length=100, verbose_name='한 줄 소개'),
        ),
        migrations.AddField(
            model_name='band',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='밴드 목록에 공개'),
        ),
        migrations.AddField(
            model_name='band',
            name='school',
            field=models.CharField(blank=True, max_length=50, verbose_name='학교/단체명'),
        ),
    ]
