# Generated by Django 6.0 on 2026-01-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0004_band_affiliation_band_affiliation_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='affiliation',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='affiliation_detail',
            new_name='department_detail',
        ),
    ]
