# Generated by Django 6.0 on 2026-01-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0005_rename_affiliation_band_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
