# Generated by Django 6.0 on 2026-01-17 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0007_alter_session_applicant_alter_session_assignee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date', 'start_index')},
            },
        ),
    ]
