# Generated by Django 6.0 on 2026-01-21 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0008_recurringexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='practice_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='합주 종료일'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='practice_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='합주 시작일'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='required_practice_count',
            field=models.IntegerField(default=1, verbose_name='곡당 주간 합주 횟수'),
        ),
        migrations.AddField(
            model_name='oneoffblock',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oneoffblock',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practiceroom',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='위치 설명'),
        ),
        migrations.CreateModel(
            name='PracticeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('is_forced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pracapp.meeting')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pracapp.practiceroom')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pracapp.song')),
            ],
            options={
                'unique_together': {('room', 'date', 'start_index')},
            },
        ),
        migrations.DeleteModel(
            name='FinalSchedule',
        ),
    ]
