# Generated by Django 6.0 on 2026-01-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0009_meeting_practice_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oneoffblock',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='oneoffblock',
            name='start_date',
        ),
        migrations.AddField(
            model_name='recurringblock',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringblock',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
