# Generated by Django 6.0 on 2026-01-21 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0010_remove_oneoffblock_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringblock',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='recurringblock',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
