# Generated by Django 6.0 on 2026-01-22 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0011_alter_recurringblock_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceroom',
            name='meeting',
        ),
        migrations.AddField(
            model_name='practiceroom',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='pracapp.band'),
        ),
    ]
