# Generated by Django 6.0 on 2026-01-22 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0012_remove_practiceroom_meeting_practiceroom_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceroom',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='pracapp.band'),
        ),
    ]
