# Generated by Django 6.0 on 2026-01-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0013_alter_practiceroom_band'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='required_practice_count',
        ),
    ]
