# Generated by Django 6.0 on 2026-02-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0014_remove_meeting_required_practice_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringexception',
            name='reason',
            field=models.CharField(default='취소', max_length=30),
        ),
        migrations.AlterField(
            model_name='oneoffblock',
            name='reason',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='recurringblock',
            name='reason',
            field=models.CharField(max_length=30),
        ),
    ]
