# Generated by Django 6.0 on 2026-02-18 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0016_oneoffblock_generated_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingFinalDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_draft', to='pracapp.meeting')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_meeting_final_drafts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
