# Generated by Django 6.0 on 2026-02-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0018_meetingscheduleconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_schedule_coordinating',
            field=models.BooleanField(default=False),
        ),
    ]
