# Generated by Django 6.0 on 2026-02-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0019_meeting_is_schedule_coordinating'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_session_application_closed',
            field=models.BooleanField(default=False),
        ),
    ]
