# Generated by Django 6.0 on 2026-02-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0020_meeting_is_session_application_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_final_schedule_released',
            field=models.BooleanField(default=False),
        ),
    ]
