# Generated by Django 6.0 on 2026-02-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0021_meeting_is_final_schedule_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_final_schedule_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
