# Generated by Django 6.0 on 2026-02-20 00:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0027_session_has_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='join_policy',
            field=models.CharField(choices=[('OPEN', '신청 즉시 참여'), ('APPROVAL', '신청 후 승인')], default='OPEN', max_length=16),
        ),
        migrations.AddField(
            model_name='meeting',
            name='visibility',
            field=models.CharField(choices=[('LISTED', '목록 공개'), ('UNLISTED', '목록 비공개(링크 전용)')], default='LISTED', max_length=16),
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', '승인 대기'), ('APPROVED', '참여 승인'), ('REJECTED', '반려'), ('LEFT', '탈퇴')], default='APPROVED', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_meeting_participants', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='pracapp.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['meeting', 'status'], name='meeting_part_status_idx'), models.Index(fields=['user', 'status'], name='meeting_user_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'user'), name='meeting_participant_unique')],
            },
        ),
    ]
