# Generated by Django 6.0 on 2026-02-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0028_meeting_join_policy_meeting_visibility_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['band', 'created_at'], name='meeting_band_created_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['band', 'visibility', 'created_at'], name='meeting_band_vis_created_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingparticipant',
            index=models.Index(fields=['user', 'status', 'meeting'], name='meeting_user_stat_meet_idx'),
        ),
    ]
