# Generated by Django 6.0 on 2026-02-20 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0029_meeting_meeting_band_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomblock',
            name='source_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_room_blocks', to='pracapp.meeting'),
        ),
        migrations.AddIndex(
            model_name='roomblock',
            index=models.Index(fields=['room', 'date', 'start_index'], name='roomblock_room_date_start_idx'),
        ),
        migrations.AddIndex(
            model_name='roomblock',
            index=models.Index(fields=['source_meeting', 'date'], name='roomblock_source_date_idx'),
        ),
    ]
