# Generated by Django 6.0 on 2026-02-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0030_roomblock_source_meeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_booking_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
