# Generated by Django 6.0 on 2026-02-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0031_meeting_is_booking_in_progress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingscheduleconfirmation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='meeting',
            name='schedule_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='meetingscheduleconfirmation',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='meetingscheduleconfirmation',
            unique_together={('meeting', 'user', 'version')},
        ),
    ]
