# Generated by Django 6.0 on 2026-02-21 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0032_alter_meetingscheduleconfirmation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingWorkDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.JSONField(default=list)),
                ('match_params', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_drafts', to='pracapp.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_work_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['meeting', 'user'], name='mwd_meeting_user_idx')],
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
