# Generated by Django 6.0 on 2026-02-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0033_meetingworkdraft'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meetingscheduleconfirmation',
            index=models.Index(fields=['meeting', 'version'], name='msc_meeting_version_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingscheduleconfirmation',
            index=models.Index(fields=['meeting', 'version', 'user'], name='msc_meet_ver_user_idx'),
        ),
        migrations.AddIndex(
            model_name='oneoffblock',
            index=models.Index(fields=['user', 'date', 'is_generated'], name='ob_user_date_gen_idx'),
        ),
        migrations.AddIndex(
            model_name='oneoffblock',
            index=models.Index(fields=['source_meeting', 'is_generated', 'date'], name='ob_src_gen_date_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringblock',
            index=models.Index(fields=['user', 'start_date', 'end_date'], name='rb_user_start_end_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringblock',
            index=models.Index(fields=['user', 'day_of_week', 'start_index'], name='rb_user_day_start_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringexception',
            index=models.Index(fields=['user', 'date'], name='rex_user_date_idx'),
        ),
    ]
