# Generated by Django 6.0 on 2026-02-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0034_meetingscheduleconfirmation_msc_meeting_version_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='performance_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='공연 일시'),
        ),
    ]
