# Generated by Django 6.0 on 2026-02-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0035_meeting_performance_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='join_policy',
            field=models.CharField(choices=[('OPEN', '신청 즉시 참여'), ('APPROVAL', '승인 후 참여')], default='OPEN', max_length=16),
        ),
        migrations.AlterField(
            model_name='practiceroom',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='pracapp.band'),
        ),
    ]
