# Generated by Django 6.0 on 2026-02-21 20:16

from django.db import migrations, models
from django.db.models import Count


def dedupe_membership_rows(apps, schema_editor):
    Membership = apps.get_model('pracapp', 'Membership')

    role_rank = {
        'LEADER': 3,
        'MANAGER': 2,
        'MEMBER': 1,
    }

    duplicated_pairs = (
        Membership.objects.values('user_id', 'band_id')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )

    for pair in duplicated_pairs:
        rows = list(
            Membership.objects.filter(
                user_id=pair['user_id'],
                band_id=pair['band_id'],
            )
        )
        rows.sort(
            key=lambda r: (
                int(bool(r.is_approved)),
                role_rank.get(str(r.role or 'MEMBER'), 0),
                int(getattr(r, 'date_joined').timestamp()) if getattr(r, 'date_joined', None) else 0,
            ),
            reverse=True,
        )
        keep = rows[0]
        Membership.objects.filter(
            user_id=pair['user_id'],
            band_id=pair['band_id'],
        ).exclude(id=keep.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0036_alter_meeting_join_policy_alter_practiceroom_band'),
    ]

    operations = [
        migrations.RunPython(dedupe_membership_rows, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'band'), name='membership_user_band_unique'),
        ),
    ]
