# Generated by Django 6.0 on 2026-02-24 04:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0038_meetingparticipant_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='join_policy',
            field=models.CharField(choices=[('OPEN', '바로 참가'), ('APPROVAL', '승인 필요')], default='OPEN', max_length=16),
        ),
        migrations.CreateModel(
            name='ExtraPracticeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_extra_practices', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_practice_schedules', to='pracapp.meeting')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_practice_schedules', to='pracapp.practiceroom')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_practice_schedules', to='pracapp.song')),
            ],
            options={
                'indexes': [models.Index(fields=['meeting', 'song'], name='eps_meeting_song_idx'), models.Index(fields=['meeting', 'date'], name='eps_meeting_date_idx'), models.Index(fields=['room', 'date', 'start_index'], name='eps_room_date_start_idx')],
                'unique_together': {('room', 'date', 'start_index')},
            },
        ),
    ]
