# Generated by Django 6.0 on 2026-02-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0043_meetingfinaldraft_match_params'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['band', 'practice_start_date', 'practice_end_date'], name='meeting_band_prac_range_idx'),
        ),
        migrations.AddIndex(
            model_name='roomblock',
            index=models.Index(fields=['source_meeting', 'room', 'date', 'start_index'], name='roomblock_src_r_d_s_idx'),
        ),
    ]
